@url = http://localhost:4400

GET {{url}}/posts

###
POST {{url}}/posts
Content-Type: application/json

{
  "post":"Testing from TEST API",
  "thumbnail": "image1.png"
}

###
PUT {{url}}/posts
Content-Type: application/json

{
  "ID": 8,
  "post": "updated"
}

###
DELETE {{url}}/posts/9
Content-Type:  application/json

{
  "ID":11
}

###
POST {{url}}/upload
Content-Type: multipart/form-data; boundary=imageboundary

--imageboundary 
Content-Disposition: form-data; name="image"; filename="image1.jpg" 
Content-Type: image/png

< ./image1.jpg
--imageboundary--

